spring:

  datasource:
    driver-class-name: org.h2.Driver
#    url: jdbc:h2:mem:test
    url: jdbc:h2:./data/test
    username: sa
    password:
#  sql:
#    init:
#      mode: always
  h2:
    console:
      enabled: true
      path: /h2-console

#MyBatis
mybatis:
  type-aliases-package: hpPrice.domain
  configuration:
    map-underscore-to-camel-case: true
  mapper-locations: classpath:mapper/*.xml

logging:
  level:
    hp_price:
      repository:
        mybatis: trace

