----MySQL
--CREATE TABLE MEMBER
--(
--   MEMBER_ID BIGINT NOT NULL AUTO_INCREMENT,
--   SIGNUP_DATE DATETIME,
--   LOGIN_ID VARCHAR(30),
--   PASSWORD VARCHAR(30),
--   ADDRESS VARCHAR(200),
--   USERNAME VARCHAR(30),
--   PRIMARY KEY (MEMBER_ID)
--);


--H2

CREATE TABLE POST
(
   POST_NUM BIGINT NOT NULL,
   W_DATE DATETIME NOT NULL,
   TITLE VARCHAR(1000) NOT NULL,
   URL VARCHAR(1000) NOT NULL,
   NICKNAME VARCHAR(500) NOT NULL,
   USER_ID VARCHAR(500) NOT NULL,
   USER_URL VARCHAR(1000) NOT NULL,
   PRIMARY KEY (POST_NUM)
);

