----MySQL
--CREATE TABLE MEMBER
--(
--   MEMBER_ID BIGINT NOT NULL AUTO_INCREMENT,
--   SIGNUP_DATE DATETIME,
--   LOGIN_ID VARCHAR(30),
--   PASSWORD VARCHAR(30),
--   ADDRESS VARCHAR(200),
--   USERNAME VARCHAR(30),
--   PRIMARY KEY (MEMBER_ID)
--);


--H2

CREATE TABLE POST
(
   POST_NUM BIGINT NOT NULL,
   W_DATE DATETIME NOT NULL,
   TITLE VARCHAR(400) NOT NULL,
   URL VARCHAR(200) NOT NULL,
   NICKNAME VARCHAR(200) NOT NULL,
   USER_ID VARCHAR(200),
   USER_URL VARCHAR(200),
   PRIMARY KEY (POST_NUM)
);

